# cv2.imread

`image[Height, Width, Channel]`

`print(image)` output
```
[[[  0   0 248]
  [  1 248   0]]

 [[246   0   0]
  [  1 244 246]]

 [[243   1 244]
  [243 242   0]]

 [[237 239 240]
  [  2   3   1]]]
```

`print(image)` expanded output
```
[
  [
    [  0   0 248] [  1 248   0]
  ]

  [
    [246   0   0] [  1 244 246]
  ]

  [
    [243   1 244] [243 242   0]
  ]
  [
    [237 239 240] [  2   3   1]
  ]
]
```

In [1]:
import cv2
import numpy as np

image = cv2.imread("1-rgb2x4.jpg")
print("image.shape")
print(image.shape)
print("image")
print(image)
print("image[:,:,1]")
print(image[:,:,1])

image.shape
(4, 2, 3)
image
[[[  0   0 248]
  [  1 248   0]]

 [[246   0   0]
  [  1 244 246]]

 [[243   1 244]
  [243 242   0]]

 [[237 239 240]
  [  2   3   1]]]
image[:,:,1]
[[  0 248]
 [  0 244]
 [  1 242]
 [239   3]]
