# What is cv2.LUT?

cv2.LUT is a function in OpenCV that applies a lookup table (LUT) to an image. This function is useful for modfying pixel values according to predefeined table.
It is often used for operations like gamma correction contrast adjustment, and color mapping.

![gamma correction](./1-gamma-correction.png)

Equation is from the literature "A Data-Centric Solution to NonHomogeneous Dehazing via Vision Transformer"

In code

```
import numpy as np
import cv2

gamma = 0.85
invGamma = 1 / gamma
table = [ ( (i/255) ** invGamma ) * 255 for i in range(256) ]
table = np.array(table, np.uint8)
image = cv2.imread("2-rgb2x4.jpg")
cv2.LUT(image[:,:,0], table)
```

For gamma value of 0.85, the inverse gamma is 1.176
This table maps each possible value (0-255) to a new value according to the gamma correction formula

`print(image[:,:,1])` output
```
[[  0 248]  -> focus on 248
 [  0 244]
 [  1 242]
 [239   3]]
```
In the table, item index 248's value is 246. So, `cv2.LUT(image([:,:,1, table])) will change the value from 248 to 246

In [12]:
import numpy as np
import cv2

gamma = 0.85
invGamma = 1 / gamma
table = [ ( (i/255) ** invGamma ) * 255 for i in range(256) ]
table = np.array(table, np.uint8)
image = cv2.imread("2-rgb2x4.jpg")
print("table[248]")
print(table[248])
print("image[:,:,1])")
print(image[:,:,1])
print("cv2.LUT(image[:,:,1], table)")
print(cv2.LUT(image[:,:,1], table))

table[248]
246
image[:,:,1])
[[  0 248]
 [  0 244]
 [  1 242]
 [239   3]]
cv2.LUT(image[:,:,1], table)
[[  0 246]
 [  0 242]
 [  0 239]
 [236   1]]


# What is np.dstack?

1. To make it easy to understand.

   `np.dstack` combines two 1-D array to one 2-D array.

2. To make it easy to understand for application.

   `np.dstack` combines Blue, Green, Red channels into a BGR image.
   
   For example, a Blue channel of a 4x2 image have a shape (4, 2). After Blue, Green, Red channels combine, it will have a shape of (4, 2, 3), where (height, width, channel).

The example below is an 4 x 2 x 3 image.

In [4]:
import numpy as np

image_B = np.array([[   0,   1],
                    [   2,   3],
                    [   4,   5],
                    [   6,   7]])
image_G = np.array([[   8,   9],
                    [  10, 11],
                    [  12, 13],
                    [  14, 15]])
image_R = np.array([[  16, 17],
                    [  18, 19],
                    [  20, 21],
                    [  22, 23]])
image_BGR = np.dstack((image_B, image_G, image_R))
print("image_B.shape")
print(image_B.shape)
print("image_BGR.shape")
print(image_BGR.shape)
print("image_BGR")
print(image_BGR)

image_B.shape
(4, 2)
image_BGR.shape
(4, 2, 3)
image_BGR
[[[ 0  8 16]
  [ 1  9 17]]

 [[ 2 10 18]
  [ 3 11 19]]

 [[ 4 12 20]
  [ 5 13 21]]

 [[ 6 14 22]
  [ 7 15 23]]]


# Application

In [2]:
import cv2
import numpy as np

def gammaCorrection(src: cv2.typing.MatLike, gamma: float) -> cv2.typing.MatLike:
    invGamma = 1 / gamma

    table = [ ( (i / 255) ** invGamma ) * 255 for i in range(256) ]
    table = np.array(table, np.uint8)

    srcGammaCorrected = cv2.LUT(src, table)

    return srcGammaCorrected

def do_gamma_correction(filename: str, gamma_B: float, gamma_G: float, gamma_R: float) -> cv2.typing.MatLike:
    image = cv2.imread(filename)

    # do gamma correction
    gammaImage_B = gammaCorrection(image[:,:,0], gamma_B)
    gammaImage_G = gammaCorrection(image[:,:,1], gamma_G)
    gammaImage_R = gammaCorrection(image[:,:,2], gamma_R)
    gammaImage = np.dstack((gammaImage_B, gammaImage_G, gammaImage_R))

    return gammaImage

image_gamma_corrected = do_gamma_correction("2-rgb2x4.jpg", gamma_B=1, gamma_G=0.85, gamma_R=0.72)

print(image_gamma_corrected)

# save the gamma corrected image
cv2.imwrite("2-rgb2x4-gamma-corrected.png", image_gamma_corrected)

[[[  0   0 245]
  [  1 246   0]]

 [[246   0   0]
  [  1 242 242]]

 [[243   0 239]
  [243 239   0]]

 [[237 236 234]
  [  2   1   0]]]


True