# How does `torch.nn.Linear` works?

`torch.nn.Linear` works by performing a matrix multiplication of the input data with weight matrix and adding the bias term.

$$input \cdot weight + bias$$

Reference:
1. https://docs.kanaries.net/topics/Python/nn-linear

In [4]:
import torch
import torch.nn as nn

m = nn.Linear(2, 3)
input = torch.tensor([[1.,2.],
                      [3.,4.]])
output = m(input)
print("input.shape")
print(input.shape)
print("input")
print(input)
print("m.weight.shape")
print(m.weight.shape)
print("m.weight")
print(m.weight)
print("m.bias")
print(m.bias)
print("output.size()")
print(output.size())
print("output")
print(output)

input.shape
torch.Size([2, 2])
input
tensor([[1., 2.],
        [3., 4.]])
m.weight.shape
torch.Size([3, 2])
m.weight
Parameter containing:
tensor([[-0.1454,  0.2193],
        [-0.6932, -0.0976],
        [ 0.1645,  0.5521]], requires_grad=True)
m.bias
Parameter containing:
tensor([-0.5549, -0.2186, -0.6164], requires_grad=True)
output.size()
torch.Size([2, 3])
output
tensor([[-0.2618, -1.1070,  0.6524],
        [-0.1140, -2.6885,  2.0856]], grad_fn=<AddmmBackward0>)


In [11]:
# see cell's output above
# matrix multiplication
output = torch.zeros((2,3))
output[0][0] = (1. * (-0.1454) + 2. * 0.2193) + (-0.5549)
output[0][1] = (1. * (-0.6932) + 2. * -0.0976) + (-0.2186)
# and so on
print(output)

tensor([[-0.2617, -1.1070,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])
